In [2]:
import wildqat as wq
import numpy as np
a = wq.opt()

In [3]:
ret = np.diag([-0.026,-0.031,-0.007,-0.022,-0.010,-0.055])
print(ret)

[[-0.026  0.     0.     0.     0.     0.   ]
 [ 0.    -0.031  0.     0.     0.     0.   ]
 [ 0.     0.    -0.007  0.     0.     0.   ]
 [ 0.     0.     0.    -0.022  0.     0.   ]
 [ 0.     0.     0.     0.    -0.01   0.   ]
 [ 0.     0.     0.     0.     0.    -0.055]]


In [4]:
ris = [[0,0.0015,0.0012,0.0018,0.0022,0.0012],[0,0,0.0017,0.0022,0.0005,0.0019],[0,0,0,0.0040,0.0032,0.0024],[0,0,0,0,0.0012,0.0076],[0,0,0,0,0,0.0021],[0,0,0,0,0,0]]

print(ris)

[[0, 0.0015, 0.0012, 0.0018, 0.0022, 0.0012], [0, 0, 0.0017, 0.0022, 0.0005, 0.0019], [0, 0, 0, 0.004, 0.0032, 0.0024], [0, 0, 0, 0, 0.0012, 0.0076], [0, 0, 0, 0, 0, 0.0021], [0, 0, 0, 0, 0, 0]]


In [5]:
a.qubo = ret + np.asarray(ris)*0.5
print(a.qubo)

[[-0.026    0.00075  0.0006   0.0009   0.0011   0.0006 ]
 [ 0.      -0.031    0.00085  0.0011   0.00025  0.00095]
 [ 0.       0.      -0.007    0.002    0.0016   0.0012 ]
 [ 0.       0.       0.      -0.022    0.0006   0.0038 ]
 [ 0.       0.       0.       0.      -0.01     0.00105]
 [ 0.       0.       0.       0.       0.      -0.055  ]]


In [6]:
a.qubo += wq.sel(6,2)
print(a.qubo)

[[-3.026    2.00075  2.0006   2.0009   2.0011   2.0006 ]
 [ 0.      -3.031    2.00085  2.0011   2.00025  2.00095]
 [ 0.       0.      -3.007    2.002    2.0016   2.0012 ]
 [ 0.       0.       0.      -3.022    2.0006   2.0038 ]
 [ 0.       0.       0.       0.      -3.01     2.00105]
 [ 0.       0.       0.       0.       0.      -3.055  ]]


In [7]:
a.sa()

[0, 0, 0, 1, 0, 1]

In [8]:
a.plot()

<Figure size 640x480 with 1 Axes>